jwt:
  secret: mysupercomplexsecret

server:
  error:
    path: /user/error
    whitelabel:
      enabled: false

spring:
  autoconfigure:
    #exclude: import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
  datasource:
    url: jdbc:mysql://localhost:3306/securecapita
    password: Ls4934506
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: familyfirstsoftwaresolutions@gmail.com
    password: jlwp jymk dxua rkwg
    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true